server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    password: 123456
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/user/**
#          filters:
#            - StripPrefix=1
